### ISSUE TITLE
Set up a basic project structure

### ISSUE THREAD

**Issue by mutheud** [mutheud/slackbot#1]
- [x] set up project folder structure
- [x] Define a requirements file; Developer Requirements file
- [x] Add a readme file

**Comment by mutheud** [comment]
Project folder structure
slack/
│
├── slack/
│   ├── __init__.py
│   ├──slack.py
│
├── tests/
│   ├── slack_tests.py
│
├── .gitignore
├── LICENSE
├── README.md
├── requirements.txt
└── setup.py


Setup.py- Package and distribution management.
Requirements.txt - It should specify the dependencies required to contribute to the project
Tests - Package Integration and unit tests 

pip install requirements-dev.txt -> Dependencies needed for the development of the application.
pip install requirements.txt -> file listing all the dependencies for a specific Python project. (running application)

README file
Prerequisite
We need to have python3 installed
	sudo apt-get update
sudo apt-get install python3.9

Installation 

Slack API documentation: https://api.slack.com/web

In this application, I am integrating slack so that my application so as to have the ability to send and receive messages from one user to the other in the same slack channel.
@DavisRayM

**Comment by DavisRayM** [comment]
@mutheud Cool, a few things:

- Going to guess the top-level `slack` directory is the repository ? 
- Let's not use the name `slack` for the directories; Perhaps something like `app`?
- Can we move the slack.py file to another folder perhaps `app/libs/slack.py`? Since I'm guessing that'll just contain utility functions/classes to use when using the slack api ? And, it's most likely not going to be the only library you create or use in this project
